# Generated by Django 3.2.4 on 2021-06-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_privatephoto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatedocument",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="privatedocument",
            name="date_updated",
        ),
        migrations.RemoveField(
            model_name="privatephoto",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="privatephoto",
            name="date_updated",
        ),
        migrations.RemoveField(
            model_name="publicdocument",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="publicdocument",
            name="date_updated",
        ),
    ]
